const courseInfo = [
    {
      icon: "flaticon-engineer",
      title: "Basic Fundamentals for Software Engineering",
      fullrating: "fas fa-star",
      halfrating: "fas fa-star-half",
      totalrating: "(4.5) (74,983 ratings)",
      name: "by Ranchor Das Chanchad",
      duration: "50 lectures (190 hrs)",
      originalprice: "₹4480",
      discountprice: "(90% off) ₹448",
    },
    {
      icon: "flaticon-paint-palette",
      title: "Enhancing Adobe Photoshop CC 2020 Skills",
      fullrating: "fas fa-star",
      halfrating: "fas fa-star-half",
      totalrating: "(4.4) (68,387 ratings)",
      name: "by Prabhu Deva",
      duration: "78 lectures (148 hrs)",
      originalprice: "₹4480",
      discountprice: "(90% off) ₹448",
    },
    {
      icon: "flaticon-coding",
      title: "HTML, CSS, and Javascript for Web Developers",
      fullrating: "fas fa-star",
      halfrating: "fas fa-star-half",
      totalrating: "(4.7) (128,458 ratings)",
      name: "by Jatin Sharma",
      duration: "85 lectures (112 hrs)",
      originalprice: "₹4480",
      discountprice: "(90% off) ₹448",
    },
    {
      icon: "flaticon-computer-science",
      title: "The Complete Android N Development Course",
      fullrating: "fas fa-star",
      halfrating: "fas fa-star-half",
      totalrating: "(4.2) (43,834 ratings)",
      name: "by Saurabh Sahu",
      duration: "85 lectures (112 hrs)",
      originalprice: "₹4480",
      discountprice: "(90% off) ₹448",
    },
    {
      icon: "flaticon-paint-palette",
      title: "The Art & Science of Drawing / BASIC SKILLS",
      fullrating: "fas fa-star",
      halfrating: "fas fa-star-half",
      totalrating: "(4.7) (10,115 ratings)",
      name: "by Akshat jain",
      duration: "28 lectures (12.5 hrs)",
      originalprice: "₹4480",
      discountprice: "(90% off) ₹448",
    },
    {
      icon: "flaticon-algorithm",
      title: "Complete Fitness Trainer: Beginner To Advanced",
      fullrating: "fas fa-star",
      halfrating: "fas fa-star-half",
      totalrating: "(4.7) (5,782 ratings)",
      name: "by Shubham Yadav",
      duration: "15 lectures (7.8 hrs)",
      originalprice: "₹4480",
      discountprice: "(90% off) ₹448",
    },
    {
      icon: "flaticon-paint-palette",
      title: "The Art & Science of Drawing / BASIC SKILLS",
      fullrating: "fas fa-star",
      halfrating: "fas fa-star-half",
      totalrating: "(4.7) (10,115 ratings)",
      name: "by Akshat jain",
      duration: "28 lectures (12.5 hrs)",
      originalprice: "₹4480",
      discountprice: "(90% off) ₹448",
    },
    {
      icon: "flaticon-coding",
      title: "HTML, CSS, and Javascript for Web Developers",
      fullrating: "fas fa-star",
      halfrating: "fas fa-star-half",
      totalrating: "(4.7) (128,458 ratings)",
      name: "by Jatin Sharma",
      duration: "85 lectures (112 hrs)",
      originalprice: "₹4480",
      discountprice: "(90% off) ₹448",
    },
    {
      icon: "flaticon-algorithm",
      title: "Complete Fitness Trainer: Beginner To Advanced",
      fullrating: "fas fa-star",
      halfrating: "fas fa-star-half",
      totalrating: "(4.7) (5,782 ratings)",
      name: "by Shubham Yadav",
      duration: "15 lectures (7.8 hrs)",
      originalprice: "₹4480",
      discountprice: "(90% off) ₹448",
    },
  ];

  export default courseInfo;